In [1]:
!pip install numpy

In [2]:
import numpy as np
my_array = np.array([1, 2, 3])
print(my_array)

[1 2 3]


In [4]:
a = np.array([3,2,3])

In [8]:
print(a)

[3 2 3]


In [9]:
a

array([3, 2, 3])

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(0.1,0.02)

array([], dtype=float64)

In [15]:
np.append(a, 1)

array([3, 2, 3, 1])

In [17]:
mylist = [3,2,3,5,6]

mylist.append([2,3])
mylist[-1]

[2, 3]

In [18]:
np.append(a, [2,3])

array([3, 2, 3, 2, 3])

In [21]:
np.delete(a, 2)

array([3, 2])

In [25]:
np.delete(a,[])

array([3, 2, 3])

In [26]:
arr = np.array([10,4,3,19,2,1,5,18])

In [27]:
np.sort(arr)

array([ 1,  2,  3,  4,  5, 10, 18, 19])

## Shape and Size

In [28]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ])

In [30]:
arr

array([10,  4,  3, 19,  2,  1,  5, 18])

In [31]:
arr.shape

(8,)

In [32]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
arr2.ndim

2

In [36]:
arr.size

8

In [37]:
arr2.size

12

## Reshaping Array

In [38]:
print(arr)
print(arr.shape)

[10  4  3 19  2  1  5 18]
(8,)


In [39]:
arr.reshape(4,2)

array([[10,  4],
       [ 3, 19],
       [ 2,  1],
       [ 5, 18]])

In [41]:
arr_reshape=arr.reshape(2,4)

In [42]:
arr_reshape.ndim

2

In [43]:
arr.reshape(2,2,2)

array([[[10,  4],
        [ 3, 19]],

       [[ 2,  1],
        [ 5, 18]]])

In [44]:
arr[np.newaxis].shape

(1, 8)

In [45]:
arr.reshape(1,8)

array([[10,  4,  3, 19,  2,  1,  5, 18]])

In [46]:
arr.reshape(8,1)

array([[10],
       [ 4],
       [ 3],
       [19],
       [ 2],
       [ 1],
       [ 5],
       [18]])

In [51]:
arr[: , np.newaxis]

array([[10],
       [ 4],
       [ 3],
       [19],
       [ 2],
       [ 1],
       [ 5],
       [18]])

In [48]:
arr[: , np.newaxis].shape

(8, 1)

In [49]:
np.expand_dims(arr,axis=0)

array([[10,  4,  3, 19,  2,  1,  5, 18]])

In [50]:
np.expand_dims(arr,axis=1)

array([[10],
       [ 4],
       [ 3],
       [19],
       [ 2],
       [ 1],
       [ 5],
       [18]])

## Indexing and Slicing

In [52]:
mylist = [1,2,3,4,5,6,7,8]

In [53]:
mylist[1:4]

[2, 3, 4]

In [54]:
mylist[-3]

6

In [62]:
data = np.array([1,2,3,4,5,6,7,8])

In [63]:
data[1:4]

array([2, 3, 4])

In [64]:
data[-2:]

array([7, 8])

In [65]:
data[data >= 4]

array([4, 5, 6, 7, 8])

In [66]:
data[data%2 == 0]

array([2, 4, 6, 8])

In [68]:
data[(data > 3) & (data%2==0)]

array([4, 6, 8])

In [69]:
arr

array([10,  4,  3, 19,  2,  1,  5, 18])

In [70]:
arr1 = arr[:4]
arr2 = arr[4:] 

In [71]:
arr1

array([10,  4,  3, 19])

In [72]:
arr2

array([ 2,  1,  5, 18])

In [73]:
np.vstack((arr1,arr2))

array([[10,  4,  3, 19],
       [ 2,  1,  5, 18]])

In [75]:
a1 = np.array([
    [1,1]
    ,[2,2]
])
a2 = np.array([
    [3,3]
    ,[4,4]
])

In [76]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [78]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [79]:
arrsplit = np.array([
    [1,2,3,4,5,6,7,8,9,10,11,12]
    ,[13,14,15,16,17,18,19,20,21,22,23,24]
])

In [80]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [81]:
np.hsplit(arrsplit,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

## Copy Array

In [82]:
arr

array([10,  4,  3, 19,  2,  1,  5, 18])

In [84]:
arr2 = arr.copy()

In [85]:
arr2*2

array([20,  8,  6, 38,  4,  2, 10, 36])

## Basic Operations

In [86]:
v1 = np.array([2,3,5])
v2 = np.array([1,2,2])

In [87]:
v1+v2

array([3, 5, 7])

In [88]:
v2-v1

array([-1, -1, -3])

In [89]:
v1*v2

array([ 2,  6, 10])

In [90]:
v1/v2

array([2. , 1.5, 2.5])

In [91]:
v2/v1

array([0.5       , 0.66666667, 0.4       ])

In [92]:
data.sum()

36

In [93]:
a1

array([[1, 1],
       [2, 2]])

In [94]:
a1.sum(axis=0)

array([3, 3])

In [95]:
v1

array([2, 3, 5])

In [96]:
v1* 0.5

array([1. , 1.5, 2.5])

In [97]:
v1 * 5

array([10, 15, 25])

In [101]:
M = np.arange(0,16).reshape(4,4)

In [102]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
M.max(axis=1)

array([ 3,  7, 11, 15])

In [104]:
M.min()

0

In [105]:
M.min(axis=1)

array([ 0,  4,  8, 12])

In [107]:
M.min(axis=0)

array([0, 1, 2, 3])

In [108]:
M.std(axis=0)

array([4.47213595, 4.47213595, 4.47213595, 4.47213595])

In [109]:
M.mean(axis=0)

array([6., 7., 8., 9.])

## Matrix

In [111]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [113]:
np.random.random((3,2))

array([[0.09848833, 0.3702194 ],
       [0.29545441, 0.54707162],
       [0.13890568, 0.96351735]])

In [114]:
mat = np.array([
    [1,2]
    ,[3,4]
])

In [115]:
ones = np.ones((2,2))

In [116]:
mat + ones

array([[2., 3.],
       [4., 5.]])

In [117]:
mat + 5

array([[6, 7],
       [8, 9]])

In [118]:
mat + np.array([2,3])

array([[3, 5],
       [5, 7]])

In [119]:
mat*mat

array([[ 1,  4],
       [ 9, 16]])

## Dot Product

In [121]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [122]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [123]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0, 1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


# Matrix Aggregation

In [124]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [125]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [126]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transposing and Reshaping

In [127]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [128]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [129]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [130]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [137]:
ndarr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [138]:
print (np.ones ( (4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [139]:
print (np.zeros ((4,3, 2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [140]:
print(np.random.random((4,3, 2)))

[[[0.33540633 0.92653884]
  [0.38118799 0.38492389]
  [0.40855522 0.79523598]]

 [[0.55356692 0.18751973]
  [0.48304338 0.0730382 ]
  [0.42286328 0.47300477]]

 [[0.15140958 0.14619467]
  [0.60289451 0.45838017]
  [0.69769937 0.33391623]]

 [[0.55382607 0.59759483]
  [0.31248887 0.09831321]
  [0.01694532 0.53589221]]]


# Flatten N-Dimensional Array

In [142]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [143]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Math Formulas

error = (1/n) * np.sum(np. square(observed - prediction))